### ISSUE TITLE
Installing on localhost

### ISSUE THREAD

**Issue by ponderingken** [varodomains/dashboard#36]
Hi Eskimo, first off thank you for this.

I have installed this into a Linux server following your directions and it works perfectly.

However I am having trouble installing it into a local environment, using windows.

I can't seem to get it right no matter what I do ?
I tried xamp, wamp, Dreamweaver, I followed your requirements of php7. 4 and MySQL, but it refuses to work in windows.

My main goal of being able to use this in windows is so I can contribute to design, 
I am not great with code but proficient with Dreamweaver and other design interfaces.

I would deeply appreciate if you can tell me, how or which " design software" is compatible with this ? 

Perhaps there is another install command beside s " compose install " ? 

I have tried for a total of 10 hours before deciding to ask, thank you in advance.

**Comment by ponderingken** [comment]
> Hi Eskimo, first off thank you for this.
> 
> I have installed this into a Linux server following your directions and it works perfectly.
> 
> However I am having trouble installing it into a local environment, using windows.
> 
> I can't seem to get it right no matter what I do ?
> I tried xamp, wamp, Dreamweaver, I followed your requirements of php7. 4 and MySQL, but it refuses to work in windows.
> 
> My main goal of being able to use this in windows is so I can contribute to design, 
> I am not great with code but proficient with Dreamweaver and other design interfaces.
> 
> I would deeply appreciate if you can tell me, how or which " design software" is compatible with this ? 
> 
> 
> Perhaps there is another install command beside s " compose install " ? 
> 
> 
> I have tried for a total of 10 hours before deciding to ask, thank you in advance.
> 

Thoughts came to mind, 
Perhaps I am viewing this wrong ? 

This is designed a application that offers a web gui, not a site designed with DNS functions ?

**Comment by eskimo** [comment]
This includes everything that is varo.domains, the DNS functionality and all. There's another repo by us called Mutual which runs on your actual nameserver.

I don't think you're going to have any luck getting this going on windows and as for dreamweaver and alternatives, I have no clue since I do everything in code. 

If you have it going on Linux you can always sshfs and modify it live like that.

**Comment by ponderingken** [comment]
> This includes everything that is varo.domains, the DNS functionality and all. There's another repo by us called Mutual which runs on your actual nameserver.
> 
> I don't think you're going to have any luck getting this going on windows and as for dreamweaver and alternatives, I have no clue since I do everything in code. 
> 
> If you have it going on Linux you can always sshfs and modify it live like that.


Thank you for the swift reply, 
I figured you did everything in code. 

Everything works great, 
And I have been using the ssh method to edit it live, to be honest I like it a lot which is why I was hoping to contribute, however I am not proficient enough to design in all code. 

Thanks again Eskimo, 
Keep up the great work & God Bless 👍
